name: AntiX-Ray
main: nl.knokko.antixray.plugin.AntiXRayPlugin
version: 0.3
load: startup
commands:
  antixray:
    description: The x-ray test command.
    aliases: [x,axr,xray,xr,antix]
    usage: /x [arguments]