name: AntiX-Ray
main: nl.knokko.xray.AntiXRay
version: 0.1
load: startup
commands:
  antixray:
    description: The x-ray test command.
    aliases: [x,axr,xray,xr,antix]
    useage: /test [arguments]